### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by beyondsmz** [lizhangqu/CoreProgress#12]
compileSdkVersion global_compileSdkVersion
    buildToolsVersion global_buildToolsVersion 
 在你的代码里都是使用 global配置的一些编译环境，请问这个是需要替换吗？还是直接改变

**Comment by lizhangqu** [comment]
apply from: "https://raw.githubusercontent.com/lizhangqu/common-gradle/master/common_version.gradle"
apply from: "https://raw.githubusercontent.com/lizhangqu/common-gradle/master/common_function.gradle"
